# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2022-2024, E36 Knots
---
- name: Install Faucet
  include_tasks: install-faucet.yml

- name: Configure Faucet
  include_tasks: config-faucet.yml

- name: Start Faucet
  include_tasks: start-faucet.yml
