# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2022-2023, E36 Knots
---
ash_cli_binary_arch: amd64
ash_cli_binary_name: "ash-linux-{{ ash_cli_binary_arch }}-v{{ ash_cli_version }}.tar.gz"
ash_cli_binary_url: "https://github.com/AshAvalanche/ash-rs/releases/download/v{{ ash_cli_version }}/{{ ash_cli_binary_name }}"

# Install directories
ash_cli_releases_dir: "{{ ash_cli_install_dir }}/releases"
ash_cli_bin_dir: "{{ ash_cli_install_dir }}/bin"

# Avalanche constants
avalanche_primary_network_id: 11111111111111111111111111111111LpoYY
