# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2022-2023, E36 Knots
---
- name: Install Ash CLI
  import_tasks: install.yml
  tags:
    - install

- name: Configure Ash CLI
  import_tasks: config.yml
  tags:
    - config
